"""empty message

Revision ID: 02438099d517
Revises: e37e4f51a9f2
Create Date: 2025-04-15 17:26:14.555595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02438099d517'
down_revision = 'e37e4f51a9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
