"""empty message

Revision ID: 271eb72062ac
Revises: 60f6c970d514
Create Date: 2025-03-18 16:08:14.884964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271eb72062ac'
down_revision = '60f6c970d514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('relationship', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('id_no', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('health_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('health_info')
        batch_op.drop_column('email')
        batch_op.drop_column('id_no')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('relationship')
        batch_op.drop_column('parent_name')

    # ### end Alembic commands ###
