"""empty message

Revision ID: 2c96ebabcfbf
Revises: 
Create Date: 2024-12-24 10:20:56.327447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c96ebabcfbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.alter_column('stream_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.alter_column('stream_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
