"""empty message

Revision ID: 3b40beebe569
Revises: 271eb72062ac
Create Date: 2025-04-10 13:56:28.940862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b40beebe569'
down_revision = '271eb72062ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('branch_manager', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('branch_head', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('branch_level', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_branch', schema=None) as batch_op:
        batch_op.drop_column('branch_level')
        batch_op.drop_column('branch_head')
        batch_op.drop_column('branch_manager')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
