"""empty message

Revision ID: 53c1c1e70853
Revises: 9f3ea94034cf
Create Date: 2025-03-01 01:04:16.871688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c1c1e70853'
down_revision = '9f3ea94034cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stream', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_roles_teacher_id', ['teacher_id'])
        batch_op.create_foreign_key('fk_roles_teacher', 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_roles_teacher', type_='foreignkey')
        batch_op.drop_constraint('uq_roles_teacher_id', type_='unique')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('stream')
        batch_op.drop_column('grade')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
