"""empty message

Revision ID: 5fea969913d6
Revises: ee40ef73070f
Create Date: 2024-12-24 10:56:35.892438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fea969913d6'
down_revision = 'ee40ef73070f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_column('x')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
