"""empty message

Revision ID: 60f6c970d514
Revises: 8366aac2773b
Create Date: 2025-03-18 16:01:51.940758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f6c970d514'
down_revision = '8366aac2773b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('email')
        batch_op.drop_column('health_info')
        batch_op.drop_column('id_no')
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('id_no', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('health_info', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('contact_phone', sa.VARCHAR(length=15), nullable=False))

    # ### end Alembic commands ###
