"""empty message

Revision ID: 66ef03ce5f5b
Revises: c39946f74d09
Create Date: 2025-04-18 09:26:31.784051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ef03ce5f5b'
down_revision = 'c39946f74d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_subject')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grades', sa.PickleType(), nullable=True))
        batch_op.alter_column('short_form',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('short_form',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('grades')

    op.create_table('_alembic_tmp_subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('grades', sa.BLOB(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), nullable=False),
    sa.Column('short_form', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
