"""empty message

Revision ID: 8366aac2773b
Revises: 4b4398eea0be
Create Date: 2025-03-15 18:28:49.514360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8366aac2773b'
down_revision = '4b4398eea0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_grade_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_grade_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('grade_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
