"""empty message

Revision ID: a19c88186b26
Revises: 66ef03ce5f5b
Create Date: 2025-04-18 18:33:46.182593
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a19c88186b26'
down_revision = '66ef03ce5f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_students_branch_id',  #
            'school_branch',
            ['branch_id'],
            ['id']
        )
        batch_op.drop_column('branch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_students_branch_id', type_='foreignkey')  # ✅ Use same name
        batch_op.drop_column('branch_id')
    # ### end Alembic commands ###
