"""empty message

Revision ID: af9535f7a33e
Revises: 5fea969913d6
Create Date: 2025-01-11 09:05:46.934638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9535f7a33e'
down_revision = '5fea969913d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('id_no',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('id_no',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
