"""empty message

Revision ID: c39946f74d09
Revises: 02438099d517
Create Date: 2025-04-17 12:35:37.468480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39946f74d09'
down_revision = '02438099d517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_form', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('grade')
        batch_op.drop_column('short_form')

    # ### end Alembic commands ###
