"""empty message

Revision ID: e5a3128e5f9b
Revises: 3b40beebe569
Create Date: 2025-04-14 18:49:33.115634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a3128e5f9b'
down_revision = '3b40beebe569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('previous_school')
        batch_op.drop_column('adm_date')
        batch_op.drop_column('relationship')
        batch_op.drop_column('dob')
        batch_op.drop_column('id_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_no', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('adm_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('previous_school', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
