"""empty message

Revision ID: ee40ef73070f
Revises: 2c96ebabcfbf
Create Date: 2024-12-24 10:47:16.295153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee40ef73070f'
down_revision = '2c96ebabcfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_column('x')

    # ### end Alembic commands ###
